# Generated by Django 3.0.3 on 2020-02-22 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumtoolHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('productBacklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrumtoolHome.ProductBacklog')),
            ],
        ),
    ]
