# Generated by Django 3.0.3 on 2020-02-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumtoolHome', '0003_taskcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcard',
            old_name='productBacklog',
            new_name='sprintBacklog',
        ),
    ]
