# Generated by Django 3.0.3 on 2020-03-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumtoolHome', '0005_adminuser_normaluser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminUser',
        ),
        migrations.DeleteModel(
            name='normalUser',
        ),
    ]
