# Generated by Django 3.0.3 on 2020-03-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumtoolHome', '0008_auto_20200303_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcard',
            name='label_backend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskcard',
            name='label_frontend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskcard',
            name='storypoints',
            field=models.IntegerField(default=0),
        ),
    ]
