# Generated by Django 3.0.3 on 2020-03-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumtoolHome', '0009_auto_20200305_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcard',
            name='label_other',
            field=models.BooleanField(default=False),
        ),
    ]
