# Generated by Django 3.0.3 on 2020-03-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumtoolHome', '0011_checklist_checklistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='name',
            new_name='text',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='number',
            field=models.IntegerField(default=0, unique=False),
        ),
    ]
