# Generated by Django 3.0.3 on 2020-03-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumtoolHome', '0012_auto_20200318_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
