# Generated by Django 3.0.3 on 2020-03-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumtoolHome', '0013_auto_20200318_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='number',
        ),
    ]
