# Generated by Django 3.0.3 on 2020-03-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumtoolHome', '0014_remove_checklistitem_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
