# Generated by Django 3.0.3 on 2020-03-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumtoolHome', '0015_checklistitem_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='number',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='numbering',
            field=models.IntegerField(default=0),
        ),
    ]
