# Generated by Django 3.0.3 on 2020-04-04 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('board_type', models.CharField(choices=[('PB', 'Product Backlog Board'), ('SP', 'Sprint Backlog Board '), ('AB', 'Archiv Board')], max_length=2)),
                ('display_lane_horizontal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
            },
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('numbering', models.IntegerField(default=0)),
                ('storypoints', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ns', 'not started'), ('do', 'done'), ('ip', 'in progress')], max_length=2)),
            ],
            options={
                'verbose_name': 'Epic(Card)',
                'verbose_name_plural': 'Epics(Card)',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('numbering', models.IntegerField(default=0)),
                ('storypoints', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ns', 'not started'), ('do', 'done'), ('ip', 'in progress')], max_length=2)),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.Epic')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('color', models.SlugField(max_length=6)),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
            },
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('numbering', models.IntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='api.Board')),
            ],
            options={
                'verbose_name': 'Lane',
                'verbose_name_plural': 'Lanes',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Steplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Steplist',
                'verbose_name_plural': 'Steplist',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('numbering', models.IntegerField(default=0)),
                ('storypoints', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ns', 'not started'), ('do', 'done'), ('ip', 'in progress')], max_length=2)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.Feature')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_cards', to='api.Label')),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_cards', to='api.Lane')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.task_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='SteplistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('checked', models.BooleanField(default=False)),
                ('numbering', models.IntegerField(default=0)),
                ('steplist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Steplist')),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Step',
            },
        ),
        migrations.AddField(
            model_name='steplist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Task'),
        ),
        migrations.AddField(
            model_name='feature',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_cards', to='api.Label'),
        ),
        migrations.AddField(
            model_name='feature',
            name='lane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_cards', to='api.Lane'),
        ),
        migrations.AddField(
            model_name='feature',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.feature_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='epic',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_cards', to='api.Label'),
        ),
        migrations.AddField(
            model_name='epic',
            name='lane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_cards', to='api.Lane'),
        ),
        migrations.AddField(
            model_name='epic',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.epic_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='board',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='api.Project'),
        ),
    ]
