# Generated by Django 3.0.3 on 2020-07-09 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'product owner'), (2, 'scrum master'), (3, 'developer')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_users', to='api.Project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_users', to='api.ProjectRole')),
            ],
            options={
                'verbose_name': 'ProjectUser',
                'verbose_name_plural': 'ProjectUsers',
            },
        ),
        migrations.RemoveField(
            model_name='scrumuser',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='scrum_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
