# Generated by Django 3.0.3 on 2020-04-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature(Card)', 'verbose_name_plural': 'Features(Card)'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task(Card)', 'verbose_name_plural': 'Tasks(Card)'},
        ),
        migrations.RemoveField(
            model_name='epic',
            name='label',
        ),
        migrations.AddField(
            model_name='epic',
            name='label',
            field=models.ManyToManyField(related_name='epic_cards', to='api.Label'),
        ),
        migrations.RemoveField(
            model_name='feature',
            name='label',
        ),
        migrations.AddField(
            model_name='feature',
            name='label',
            field=models.ManyToManyField(related_name='feature_cards', to='api.Label'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='label',
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(related_name='task_cards', to='api.Label'),
        ),
    ]
