# Generated by Django 3.0.3 on 2020-09-04 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200715_2223'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sprint',
            managers=[
                ('timed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='projectuser',
            old_name='scrum_user',
            new_name='plattform_user',
        ),
        migrations.AlterField(
            model_name='epic',
            name='status',
            field=models.CharField(choices=[('NW', 'new'), ('PL', 'planned'), ('NS', 'not started'), ('DO', 'done'), ('IP', 'in progress'), ('AC', 'accepted')], default='NS', help_text='This is the name of the list itself', max_length=2),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('NW', 'new'), ('PL', 'planned'), ('NS', 'not started'), ('DO', 'done'), ('IP', 'in progress'), ('AC', 'accepted')], default='NS', help_text='This is the name of the list itself', max_length=2),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='number',
            field=models.IntegerField(help_text='An ascending number counting the sprint in the project'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('IL', 'planning'), ('PL', 'planned'), ('IR', 'in_progress'), ('DO', 'done'), ('AC', 'accepted')], default='IL', max_length=2),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='story',
            field=models.TextField(blank=True, help_text='Story of the po that he wants to do in the sprint'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='version',
            field=models.TextField(help_text='The Version of the product after the             sprint is finished (V00.00.00.00)', max_length=12, validators=[django.core.validators.RegexValidator('^V\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NW', 'new'), ('PL', 'planned'), ('NS', 'not started'), ('DO', 'done'), ('IP', 'in progress'), ('AC', 'accepted')], default='NS', help_text='This is the name of the list itself', max_length=2),
        ),
    ]
