# Generated by Django 3.0.3 on 2020-04-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200405_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='description',
            field=models.TextField(blank=True, help_text='User description of the card', null=True),
        ),
        migrations.AlterField(
            model_name='epic',
            name='name',
            field=models.CharField(help_text='User given name of the card', max_length=256),
        ),
        migrations.AlterField(
            model_name='epic',
            name='numbering',
            field=models.IntegerField(default=0, help_text='Describes the order of the steps'),
        ),
        migrations.AlterField(
            model_name='epic',
            name='status',
            field=models.CharField(choices=[('ns', 'not started'), ('do', 'done'), ('ip', 'in progress')], help_text='This is the name of the list itself', max_length=2),
        ),
        migrations.AlterField(
            model_name='epic',
            name='storypoints',
            field=models.IntegerField(default=0, help_text='This is the name of the list itself'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True, help_text='User description of the card', null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(help_text='User given name of the card', max_length=256),
        ),
        migrations.AlterField(
            model_name='feature',
            name='numbering',
            field=models.IntegerField(default=0, help_text='Describes the order of the steps'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('ns', 'not started'), ('do', 'done'), ('ip', 'in progress')], help_text='This is the name of the list itself', max_length=2),
        ),
        migrations.AlterField(
            model_name='feature',
            name='storypoints',
            field=models.IntegerField(default=0, help_text='This is the name of the list itself'),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.SlugField(help_text='The color of the label in hex (ffffff)', max_length=6),
        ),
        migrations.AlterField(
            model_name='label',
            name='title',
            field=models.CharField(help_text='This is the text the Label represents', max_length=256),
        ),
        migrations.AlterField(
            model_name='steplist',
            name='name',
            field=models.CharField(default='defaultSteplist', help_text='This is the name of the list itself', max_length=256),
        ),
        migrations.AlterField(
            model_name='steplist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steplists', to='api.Task'),
        ),
        migrations.AlterField(
            model_name='steplistitem',
            name='checked',
            field=models.BooleanField(default=False, help_text='Indicates that the step is finished'),
        ),
        migrations.AlterField(
            model_name='steplistitem',
            name='numbering',
            field=models.IntegerField(default=0, help_text='Describes the order of the steps'),
        ),
        migrations.AlterField(
            model_name='steplistitem',
            name='text',
            field=models.CharField(help_text='This is the text the user enters', max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='User description of the card', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='User given name of the card', max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='numbering',
            field=models.IntegerField(default=0, help_text='Describes the order of the steps'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ns', 'not started'), ('do', 'done'), ('ip', 'in progress')], help_text='This is the name of the list itself', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='storypoints',
            field=models.IntegerField(default=0, help_text='This is the name of the list itself'),
        ),
    ]
