# Generated by Django 3.0.3 on 2020-04-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200405_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_type',
            field=models.CharField(choices=[('PB', 'Product Backlog Board'), ('SP', 'Sprint Backlog Board '), ('AB', 'Archiv Board')], help_text='This represents the type of board', max_length=2),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, help_text='User description of the card', null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(help_text='This represents the name of the lane', max_length=256),
        ),
        migrations.AlterField(
            model_name='epic',
            name='status',
            field=models.CharField(choices=[('ns', 'not started'), ('do', 'done'), ('ip', 'in progress')], default='ns', help_text='This is the name of the list itself', max_length=2),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('ns', 'not started'), ('do', 'done'), ('ip', 'in progress')], default='ns', help_text='This is the name of the list itself', max_length=2),
        ),
        migrations.AlterField(
            model_name='lane',
            name='name',
            field=models.CharField(help_text='This represents the name of the lane', max_length=256),
        ),
        migrations.AlterField(
            model_name='lane',
            name='numbering',
            field=models.IntegerField(default=0, help_text='Describes the order of the lanes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='User description of the card', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='This represents the name of the lane', max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ns', 'not started'), ('do', 'done'), ('ip', 'in progress')], default='ns', help_text='This is the name of the list itself', max_length=2),
        ),
    ]
