# Generated by Django 3.0.3 on 2020-09-21 09:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200904_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSprint',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start', models.DateField(blank=True, help_text='Begin of the project', null=True)),
                ('end', models.DateField(blank=True, help_text='End of the project', null=True)),
                ('version', models.TextField(help_text='The Version of the product after the             sprint is finished (V00.00.00.00)', max_length=12, validators=[django.core.validators.RegexValidator('^V\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$')])),
                ('number', models.IntegerField(help_text='An ascending number counting the sprint in the project')),
                ('story', models.TextField(blank=True, help_text='Story of the po that he wants to do in the sprint')),
                ('status', models.CharField(choices=[('IL', 'planning'), ('PL', 'planned'), ('IR', 'in_progress'), ('DO', 'done'), ('AC', 'accepted')], default='IL', max_length=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, help_text='Project this sprint object is part of.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Project')),
            ],
            options={
                'verbose_name': 'historical Sprint',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
