# Generated by Django 3.0.3 on 2020-07-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200712_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='lane',
            name='board',
            field=models.ForeignKey(default=1, help_text='The board this lane is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='api.Board'),
            preserve_default=False,
        ),
    ]
