# Generated by Django 3.0.3 on 2020-04-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200405_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epic',
            old_name='label',
            new_name='labels',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='label',
            new_name='labels',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='label',
            new_name='labels',
        ),
    ]
