# Generated by Django 3.0.3 on 2020-09-21 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_historicalsprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='User given name of the card', max_length=256)),
                ('description', models.TextField(blank=True, help_text='User description of the card', null=True)),
                ('numbering', models.IntegerField(default=0, help_text='Describes the order of the steps')),
                ('storypoints', models.IntegerField(default=0, help_text='This is the name of the list itself')),
                ('status', models.CharField(choices=[('NW', 'new'), ('PL', 'planned'), ('NS', 'not started'), ('DO', 'done'), ('IP', 'in progress'), ('AC', 'accepted')], default='NS', help_text='This is the name of the list itself', max_length=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('feature', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Feature')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lane', models.ForeignKey(blank=True, db_constraint=False, help_text='Lane this card belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Lane')),
                ('sprint', models.ForeignKey(blank=True, db_constraint=False, help_text='Sprint this card is part of.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Sprint')),
            ],
            options={
                'verbose_name': 'historical Task(Card)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFeature',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='User given name of the card', max_length=256)),
                ('description', models.TextField(blank=True, help_text='User description of the card', null=True)),
                ('numbering', models.IntegerField(default=0, help_text='Describes the order of the steps')),
                ('storypoints', models.IntegerField(default=0, help_text='This is the name of the list itself')),
                ('status', models.CharField(choices=[('NW', 'new'), ('PL', 'planned'), ('NS', 'not started'), ('DO', 'done'), ('IP', 'in progress'), ('AC', 'accepted')], default='NS', help_text='This is the name of the list itself', max_length=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('epic', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Epic')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lane', models.ForeignKey(blank=True, db_constraint=False, help_text='Lane this card belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Lane')),
                ('sprint', models.ForeignKey(blank=True, db_constraint=False, help_text='Sprint this card is part of.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Sprint')),
            ],
            options={
                'verbose_name': 'historical Feature(Card)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEpic',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='User given name of the card', max_length=256)),
                ('description', models.TextField(blank=True, help_text='User description of the card', null=True)),
                ('numbering', models.IntegerField(default=0, help_text='Describes the order of the steps')),
                ('storypoints', models.IntegerField(default=0, help_text='This is the name of the list itself')),
                ('status', models.CharField(choices=[('NW', 'new'), ('PL', 'planned'), ('NS', 'not started'), ('DO', 'done'), ('IP', 'in progress'), ('AC', 'accepted')], default='NS', help_text='This is the name of the list itself', max_length=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lane', models.ForeignKey(blank=True, db_constraint=False, help_text='Lane this card belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Lane')),
                ('sprint', models.ForeignKey(blank=True, db_constraint=False, help_text='Sprint this card is part of.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Sprint')),
            ],
            options={
                'verbose_name': 'historical Epic(Card)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
