# Generated by Django 3.0.3 on 2020-04-07 19:29
from __future__ import unicode_literals

from django.db import migrations


def load_projects_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "project_initial")
#    call_command("loaddata", "board")
#    call_command("loaddata", "lane")


def delete_projects(apps, schema_editor):
    Store = apps.get_model("api", "project")
    Store.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200405_2004'),
    ]

    operations = [
        migrations.RunPython(load_projects_from_fixture, delete_projects),
    ]
