# Generated by Django 3.0.3 on 2020-11-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201005_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='done_on',
            field=models.DateField(blank=True, help_text='Date of task status set to done', null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='done_on',
            field=models.DateField(blank=True, help_text='Date of task status set to done', null=True),
        ),
        migrations.AddField(
            model_name='historicalepic',
            name='done_on',
            field=models.DateField(blank=True, help_text='Date of task status set to done', null=True),
        ),
        migrations.AddField(
            model_name='historicalfeature',
            name='done_on',
            field=models.DateField(blank=True, help_text='Date of task status set to done', null=True),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='done_on',
            field=models.DateField(blank=True, help_text='Date of task status set to done', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='done_on',
            field=models.DateField(blank=True, help_text='Date of task status set to done', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsprint',
            name='number',
            field=models.IntegerField(help_text='An ascending number counting the sprint in the project.         Starting with 1'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='number',
            field=models.IntegerField(help_text='An ascending number counting the sprint in the project.         Starting with 1'),
        ),
    ]
