# Generated by Django 3.0.3 on 2020-04-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200407_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='card_attachement')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.AddField(
            model_name='epic',
            name='files',
            field=models.ManyToManyField(related_name='epic_files', to='api.File'),
        ),
        migrations.AddField(
            model_name='feature',
            name='files',
            field=models.ManyToManyField(related_name='feature_files', to='api.File'),
        ),
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.ManyToManyField(related_name='task_files', to='api.File'),
        ),
    ]
