# Generated by Django 3.0.3 on 2020-04-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200408_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epic',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='task',
            name='polymorphic_ctype',
        ),
    ]
