# Generated by Django 3.0.3 on 2021-01-14 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201116_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sprint_duration',
            field=models.PositiveIntegerField(default=7, help_text='Duration of a sprint in days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
