# Generated by Django 3.0.3 on 2020-05-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200514_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='epic_files', to='api.File'),
        ),
        migrations.AlterField(
            model_name='epic',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='epic_cards', to='api.Label'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='feature_files', to='api.File'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='feature_cards', to='api.Label'),
        ),
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_files', to='api.File'),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_cards', to='api.Label'),
        ),
    ]
