# Generated by Django 3.0.3 on 2020-05-16 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200514_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.TextField(help_text='The color of the label in hex (#ffffff)', max_length=7, validators=[django.core.validators.RegexValidator('^#[A-Fa-f0-9]{6}$')]),
        ),
    ]
