# Generated by Django 3.0.3 on 2020-05-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200516_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end',
            field=models.DateField(
                blank=True, help_text='End of the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sprint_duration',
            field=models.PositiveIntegerField(
                blank=True, help_text='Duration of a sprint', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start',
            field=models.DateField(
                blank=True, help_text='Begin of the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('AR', 'Archiv'), ('AC', 'Active')],
                                   default='AC', help_text='This represents the type of board', max_length=2),
        ),
    ]
