# Generated by Django 3.0.3 on 2020-05-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200517_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board',
            new_name='project',
        ),
    ]
