# Generated by Django 3.0.3 on 2020-05-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200518_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dod',
            field=models.TextField(blank=True, help_text='Definition of Done ', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dor',
            field=models.TextField(blank=True, help_text='Definition of Ready ', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='numOfSprints',
            field=models.PositiveIntegerField(blank=True, help_text='Number of Sprints possible ', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sprint_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of a sprint in days', null=True),
        ),
    ]
